### ISSUE TITLE
Create AggregateError type

### ISSUE THREAD

**Issue by TheBrambleShark** [Nihlus/Remora.Results#1]
Sometimes, an error state needs to recommend multiple errors where an error doesn't necessarily mean aborting the entire operation. For instance, if you are uploading a set of files and each upload operation returns a `Result<TValue>`. If one fails, it should continue and move onto the next file. At the end of the operation, if all were successful, a successful result is returned. If one or more failed, an `AggregateError` is returned containing a collection of all failed results.

Proposed API:

```cs
// Non-Generic
public sealed record AggregateError(IEnumerable<ErrorResult> Errors)
{
    public ErrorResult First { get; } = Errors.First();
    public IEnumerator<ErrorResult> GetEnumerator() => Errors.GetEnumerator();
}
: ErrorResult("One or more errors occurred.");

// Generic
public sealed record AggregateError<TError>(IEnumerable<TError> Errors) where TError : ErrorResult
{
    public TResult First { get; } = Errors.First();
    public IEnumerator<TResult> GetEnumerator() => Errors.GetEnumerator();
}
: ErrorResult("One or more errors occurred.");
```

Considerations:
* The above usage assumes the provided Errors enumerable is not null or empty. Additional checks should be added to ensure this.
* I've provided the non-generic and generic versions for review, but I don't know if a non-generic version is necessary.

Usage:
```cs
var errors = List<ErrorResult>();

foreach (var file in files)
{
    var result = MyApi.Upload(file);
    if (!result.IsSuccess)
    {
        errors.Add(result);
    }
}

return errors.Any()
    ? new AggregateError(errors);
    : Result.FromSuccess();
```

**Comment by Tylertron1998** [comment]
Could the `.First` property be cached? And could this be made generic as well, so users can either use a specific single type, or (as per the example) just `ErrorResult`? Other then that, looks like a great addition.

**Comment by TheBrambleShark** [comment]
Good ideas. I've updated the proposition.

**Comment by TheBrambleShark** [comment]
Added in commit b1a4d62
