### ISSUE TITLE
Create HttpError type

### ISSUE THREAD

**Issue by TheBrambleShark** [Nihlus/Remora.Results#2]
Generic type for working with HttpClient errors.

Proposed API:
```cs
public sealed record HttpError(int ErrorCode, string Message) : base(message);
```

**Comment by Tylertron1998** [comment]
hmm, imo HttpError is a bit *too* specific to be included. Remora.Results fits better as a base library for creating errors, then a library *of* errors (if that's even the right wording). That's something that would be easy to add to your own project.

**Comment by TheBrambleShark** [comment]
This was implemented in Remora.Rest, a more suitable library for this type.
