### ISSUE TITLE
Add Result.FromResult(Result)

### ISSUE THREAD

**Issue by TheBrambleShark** [Nihlus/Remora.Results#8]
Just for parity with `Result.FromError(Result<T>)`, we should add a `Result.FromError(Result)` method that sets the inner result.

Right now this can be done by running `Result.FromError(result.Error, result)` but this can be a bit awkward at times.

```cs
public Result FromError(Result result)
    => new(result.Error, result);
```

**Comment by Nihlus** [comment]
What would be the point of using this method? It doesn't change the representation of the result nor the contained error, and just adds a level of indirection. Is there a particular use case you have in mind?

**Comment by TheBrambleShark** [comment]
Accidentally provided the wrong method name. Updated that.

I use this to keep track that it was a child that resulted in an error. I can follow the inner error down like following inner exceptions for building better diagnostics data. Right now, whether I can use `Result.FromError(child)` or `Result.FromError(child.Error, child)` depends entirely on the type of `child`.

**Comment by Nihlus** [comment]
Gotcha - the described usage seems like somewhat of an anti-pattern to me, and I'd like some more input from library users before I call it one way or the other.
